GET http://localhost:3000/scores

###

GET http://localhost:3000/scores/5ef85be81140f8f382ea5343

###


POST http://localhost:3000/scores
Content-Type: application/json

{
    "name": "Haozhi"
}

###

POST http://localhost:3000/scores
Content-Type: application/json

{
    "name": "Xinyue"
}

###

POST http://localhost:3000/scores
Content-Type: application/json

{
    "name": "Test1"
}

###

POST http://localhost:3000/scores
Content-Type: application/json

{
    "name": "Test2"
}

###

POST http://localhost:3000/scores
Content-Type: application/json

{
    "userId": "5f05231063e0fd5222d26af4",
    "rival_userId": "5f05230e63e0fd5222d26af3",
    "scores": [[50,50,50],[50,20,20],[0],[1]],
    "tags": [[50,50,50],[50,2,3],[99],[1]],
    "scores_in_3_darts": [150,150,0,1],
    "total_score": 301,
    "isWin": true
}

###

PATCH http://localhost:3000/scores/5f030fdc0e496677db19154b
Content-Type: application/json

{
    "game": 2
}

###

DELETE http://localhost:3000/scores/5f03077fd60726745abb8565