GET http://localhost:3000/scores

###

GET http://localhost:3000/scores/5ef67a93132c3a76fd7b455a

###


POST http://localhost:3000/scores
Content-Type: application/json

{
    "name": "Haozhi"
}

###

POST http://localhost:3000/scores
Content-Type: application/json

{
    "name": "Xinyue"
}

###

POST http://localhost:3000/scores
Content-Type: application/json

{
    "name": "Test1"
}

###

POST http://localhost:3000/scores
Content-Type: application/json

{
    "name": "Test2"
}

###

POST http://localhost:3000/scores
Content-Type: application/json

{
    "name": "5effe2397601f6b44c81c569",
    "game": 7,
    "scores": [
        [{"score":50,"tag":50},{"score":20,"tag":2},{"score":20,"tag":3}],
        [{"score":50,"tag":50},{"score":50,"tag":50},{"score":50,"tag":50}],
        [{"score":1,"tag":1}]
    ]
}

###

PATCH http://localhost:3000/scores/5ef7047c11e6eca512610295
Content-Type: application/json

{
    "scores": {
        "score": 10,
        "tag": 2
    }
}

###

DELETE http://localhost:3000/scores/5ef828d03a10ece6702fea92