GET http://localhost:3000/users

###

GET http://localhost:3000/users/5ef85be81140f8f382ea5343

###

POST http://localhost:3000/users
Content-Type: application/json

{
    "name": "Haozhi"
}

###

POST http://localhost:3000/users
Content-Type: application/json

{
    "name": "Xinyue"
}

###

POST http://localhost:3000/users
Content-Type: application/json

{
    "name": "Test 1"
}

###

POST http://localhost:3000/users
Content-Type: application/json

{
    "name": "Test 2"
}

###

PATCH http://localhost:3000/users/5ef85bf01140f8f382ea5344
Content-Type: application/json

{
}

###

DELETE http://localhost:3000/users/5ef6d5aefb6ec097c36a3fb6

