GET http://localhost:3000/users

###

POST http://localhost:3000/users
Content-Type: application/json

{
    "name": "Haozhi"
}

###

POST http://localhost:3000/users
Content-Type: application/json

{
    "name": "Xinyue"
}

###

POST http://localhost:3000/users
Content-Type: application/json

{
    "name": "Test1"
}

###

POST http://localhost:3000/users
Content-Type: application/json

{
    "name": "Test2"
}

###

PATCH http://localhost:3000/users/5ef5a505d0370f4a659c970d
Content-Type: application/json

{
    "name": "Test3"
}

###

DELETE http://localhost:3000/users/5ef6d5aefb6ec097c36a3fb6

